# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
print(np.__version__)
print(np.show_config())

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
x = np.array([100,20,34])
  
print("Size of the array: ",
      x.size)
  
print("Memory size of one array element in bytes: ",
      x.itemsize)

Size of the array:  3
Memory size of one array element in bytes:  8


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
x=np.zeros(10)
x[4]=1

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
v = np.arange(10,50)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
v[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
x=[1,2,0,0,4,0]
out = np.nonzero(x)
print(out)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
import numpy as np
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
x = np.random.random((3,3,3))
print(x)

[[[0.36692159 0.63648379 0.82575494]
  [0.14969328 0.2300662  0.90415763]
  [0.36820828 0.89020567 0.03687536]]

 [[0.96814922 0.66893972 0.42182854]
  [0.88316151 0.63577688 0.28025439]
  [0.98781383 0.68282874 0.44708395]]

 [[0.09116737 0.37238428 0.58299961]
  [0.74174158 0.86807206 0.19648573]
  [0.61806351 0.64301678 0.3078753 ]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
x = np.random.random((10,10))
print(x)
print("max,min", x.min(),x.max())

[[0.02453856 0.61069679 0.9498817  0.00301592 0.24265772 0.75703128
  0.74318819 0.4851035  0.42883161 0.3067764 ]
 [0.71715836 0.32183561 0.79691621 0.68752582 0.79340661 0.42548008
  0.37467364 0.90510145 0.20048213 0.19108211]
 [0.50010005 0.55631243 0.68774817 0.43819188 0.17682969 0.88391151
  0.86166912 0.63158523 0.47512879 0.84838596]
 [0.62104459 0.21685537 0.59782674 0.20512599 0.52030564 0.03724689
  0.6565263  0.04803713 0.61657937 0.63393895]
 [0.29438286 0.13259964 0.8609118  0.60958454 0.11012753 0.08957406
  0.66036203 0.46347844 0.87430222 0.74763028]
 [0.37275448 0.28076635 0.29914482 0.06325261 0.94131173 0.52758527
  0.4972374  0.22636841 0.53847447 0.38048727]
 [0.30539655 0.0388166  0.05200002 0.29979624 0.21320172 0.7468023
  0.14049112 0.34308607 0.12023331 0.93018568]
 [0.87755961 0.0616841  0.10857271 0.29558221 0.77431952 0.60452551
  0.76328814 0.19074003 0.9634581  0.49410987]
 [0.41272917 0.0334776  0.2530956  0.21127013 0.46115487 0.06156055
  0.62419328 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
x=np.random.random(10)
print(x)
print("mean:", x.mean())

[0.01110996 0.18861722 0.31133726 0.65905984 0.62173042 0.74626015
 0.1757875  0.54394174 0.61978999 0.68463494]
mean: 0.4562269022448674


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
x=np.ones([5,5])
x[1:-1, 1:-1]=0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
x = np.ones((3,3))
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
#Z[::2,1::2] = 1
print(Z)

[[0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:

Z = np.tile(np. array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z= (Z-Zmin)/(Zmax-Zmin)
print (Z)

[[0.81194247 0.28129035 0.95099414 0.79333543 0.76378778]
 [0.39639384 0.         0.38406753 0.7683669  0.45030922]
 [0.36955205 0.34852708 0.67034343 0.28178781 0.56942444]
 [0.48460062 0.7697943  0.84939398 1.         0.01892438]
 [0.64570097 0.74867037 0.67775573 0.68268363 0.14700257]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
RGBA = np.dtype([('red',np.uint8),('green',np.uint8),('blue',np.uint8),('alpha',np.uint8)])
color = np.array((1,2,4,3),dtype = RGBA)
print(color['red'])
type(color)

1


numpy.ndarray

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
arr_1 = np.random.random((5,3))
arr_2 = np.random.random((3,2))
print(arr_1 @ arr_2)
np.dot(arr_1,arr_2)

[[0.44437665 0.65895806]
 [0.87662409 0.97177073]
 [1.56188501 1.1553139 ]
 [0.43363248 0.67927122]
 [0.94780491 0.57727305]]


array([[0.44437665, 0.65895806],
       [0.87662409, 0.97177073],
       [1.56188501, 1.1553139 ],
       [0.43363248, 0.67927122],
       [0.94780491, 0.57727305]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
x = np.arange(11)
x[(x >= 3) & (x <= 8)] = -1
print(x)

[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(np.sum(range(5),-1))
from numpy import *
print(np.sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z = np.arange(3)
Z ** Z       # = [0^0, 1^1, 2^2] = [1, 1, 4]
2 << Z >> 2  # = [0, 1, 2]
Z < - Z      # = [False, False, False]
1j * Z       # = [0 + 0.j, 0 + 1.j, 0 + 2.j]
Z / 1 / 1    # = [0, 1, 2]
Z < Z > Z 

ValueError: ignored

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
x = np.random.uniform(-10, +10, 10)
np.copysign(np.ceil(np.abs(x)), x)

array([ 5.,  9., -9.,  1.,  5.,  2.,  5., -5.,  9., -1.])

#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [2]:
x = np.arange(0, 10)
y = np.arange(5, 15)
np.intersect1d(x, y)

array([5, 6, 7, 8, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [3]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [4]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [17]:
today = np.datetime64('today', 'D')
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')
print(today)
print(yesterday)
print(tomorrow)

2022-06-28
2022-06-27
2022-06-29


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [9]:
x = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
x

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [20]:
A = np.ones(3) * 1
print(A)
B = np.ones(3) * 2
print(B)
C = np.ones(3) * 3
print(C)
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)

[1. 1. 1.]
[2. 2. 2.]
[3. 3. 3.]


array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [21]:
x = np.random.uniform(-10, +10, 10)
x.astype(np.int32)
np.trunc(x)
print(x)

[ 0.34108764 -2.51934685 -4.51061491 -0.67259805  1.05049541  9.54222321
 -5.90185684  7.80936318  5.56134383  2.6163092 ]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [23]:
x = np.zeros((5, 5))
print(x)
x += np.arange(5)
print(x)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [30]:
def generate_integers():
    for i in range(10):
        yield i
        print(i)
print(generate_integers())
np.fromiter(generate_integers(), dtype=np.float32, count=-1)

<generator object generate_integers at 0x7f1d398f4cd0>
0
1
2
3
4
5
6
7
8
9


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [32]:
np.linspace(start=0.1, stop=1, num=10, endpoint=False)

array([0.1 , 0.19, 0.28, 0.37, 0.46, 0.55, 0.64, 0.73, 0.82, 0.91])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [33]:
x = np.random.random(size=10)
x.sort()

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [40]:
import time

begin_time = time.time()
print(begin_time)
x = np.arange(1000000)
print(x)
print(np.sum(x))
end_time = time.time()
print(str(1000*(end_time - begin_time)))

begin_time2 = time.time()
print(begin_time2)
x = np.arange(1000000)
np.add.reduce(x)
end_time2 = time.time()
print(str(1000*(end_time2 - begin_time2)))

1656392512.5322137
[     0      1      2 ... 999997 999998 999999]
499999500000
3.5858154296875
1656392512.5359135
4.711389541625977


#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [42]:
A = np.arange(10)
B = np.arange(11)
np.array_equal(A, B)

False

#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [45]:
x = np.zeros(10)
x.flags.writeable = False
x[1] = 1

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [55]:
Z = np.random.random((10, 2))
print(Z)
X, Y = Z[:, 0], Z[:, 1]
print(X)
print(Y)
R = np.sqrt(X ** 2 + Y ** 2)
T = np.arctan2(Y, X)
print(R)
print(T)

[[0.1320692  0.95365532]
 [0.29870458 0.97703761]
 [0.85999662 0.39940392]
 [0.85583018 0.83219199]
 [0.40310856 0.14772746]
 [0.95778385 0.74664267]
 [0.31846857 0.76067959]
 [0.22984055 0.88764858]
 [0.99356881 0.02281954]
 [0.81928166 0.90330951]]
[0.1320692  0.29870458 0.85999662 0.85583018 0.40310856 0.95778385
 0.31846857 0.22984055 0.99356881 0.81928166]
[0.95365532 0.97703761 0.39940392 0.83219199 0.14772746 0.74664267
 0.76067959 0.88764858 0.02281954 0.90330951]
[0.96275684 1.02167848 0.94821815 1.19372895 0.42932495 1.2144238
 0.82465488 0.91692239 0.99383083 1.2195042 ]
[1.43318426 1.27409578 0.43478478 0.7713956  0.35127201 0.66214792
 1.1743052  1.31742898 0.02296321 0.83413944]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [57]:
x = np.random.random(10)
x[x == np.max(x)] = 0
x[x.argmax()] = 0
x

array([0.47517672, 0.10497671, 0.37145892, 0.        , 0.47562115,
       0.0769502 , 0.40776218, 0.        , 0.64227605, 0.49505176])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [59]:
z = np.zeros((5, 5), [('x', float), ('y', float)])
z['x'], z['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
z

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [60]:
x = np.random.random((5, 5))
y = np.random.random((5, 5))
c = 1 / (x - y)
c = 1 / np.subtract.outer(x, y)
np.linalg.det(c)

array([[ 1.10822671e+08,  2.04970097e+05, -3.36995590e+04,
        -1.88518419e+05,  2.64061954e+07],
       [-8.53167003e+07,  1.44150114e+06,  2.37949717e+06,
        -1.10328612e+05, -5.45320439e+04],
       [-5.26538739e+04, -5.19630149e+04, -3.28835854e+05,
        -2.65938100e+04,  3.32925746e+06],
       [ 2.84585191e+06, -9.92542543e+04, -2.86820955e+04,
         3.21203636e+05, -9.55889091e+04],
       [-3.75618262e+04,  2.40501212e+06, -2.22885693e+04,
        -2.32328891e+06,  3.91481219e+05]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [66]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [67]:
np.set_printoptions(threshold=np.nan)
Z = np.zeros((25,25))
print(Z)

ValueError: ignored

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [4]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

50


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [3]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                   ('y', float, 1)]),
                    ('color',    [ ('r', float, 1),
                                   ('g', float, 1),
                                   ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [7]:
Z = np.random.random((10,2))
Z
X,Y = np.atleast_2d(Z[:,0]), np.atleast_2d(Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.41954067 0.34816532 0.82993784 0.37608579 0.58415475
  0.43141658 0.90984607 0.47504421 0.53507901]
 [0.41954067 0.         0.4608422  0.8324783  0.76836316 0.63115895
  0.76111297 1.09220252 0.1671834  0.36338858]
 [0.34816532 0.4608422  0.         0.48239166 0.45017699 0.23705206
  0.36013722 0.63817266 0.38306962 0.29394507]
 [0.82993784 0.8324783  0.48239166 0.         0.8122485  0.24580101
  0.65242881 0.43694573 0.6829293  0.48050379]
 [0.37608579 0.76836316 0.45017699 0.8122485  0.         0.60073
  0.16991787 0.69988604 0.77103574 0.73956275]
 [0.58415475 0.63115895 0.23705206 0.24580101 0.60073    0.
  0.4576873  0.48352764 0.503465   0.32431775]
 [0.43141658 0.76111297 0.36013722 0.65242881 0.16991787 0.4576873
  0.         0.53737811 0.72684961 0.65264628]
 [0.90984607 1.09220252 0.63817266 0.43694573 0.69988604 0.48352764
  0.53737811 0.         0.98133523 0.80777106]
 [0.47504421 0.1671834  0.38306962 0.6829293  0.77103574 0.503465
  0.72684961 0.98133523 0.

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [9]:
Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)
Z

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [10]:
Z = np.genfromtxt("missing.dat", delimiter=",")

OSError: ignored

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [4]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [5]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print (Z)

[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [6]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)
Y

array([[ 0.38332147, -0.35676413,  0.4787632 , -0.42195758, -0.23973282,
        -0.23583467,  0.12843645, -0.12454219,  0.44707149, -0.05876122],
       [ 0.22892294, -0.36343396,  0.34034445,  0.3505574 , -0.26932522,
        -0.02597898,  0.00924703, -0.12365175,  0.24245916, -0.38914107],
       [-0.4597609 ,  0.35350697,  0.14358299, -0.21001088, -0.20360259,
         0.38682261,  0.29905007,  0.02248546, -0.2950179 , -0.03705584],
       [ 0.33645496, -0.16472476,  0.19118539, -0.31229054, -0.15509176,
         0.27640001, -0.4778627 ,  0.21384733,  0.10079973, -0.00871766],
       [-0.25121681, -0.3692466 , -0.07304304,  0.13676119,  0.47690837,
         0.00766737, -0.23555198, -0.21744142,  0.29693687,  0.22822604]])

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [7]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[0 3 9]
 [0 6 5]
 [0 5 4]]
[[0 3 9]
 [0 5 4]
 [0 6 5]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [8]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [9]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5556482835184473


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [10]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [11]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [12]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution

np.add.at(Z, I, 1)
print(Z)

[1. 3. 3. 6. 1. 4. 3. 4. 3. 2.]
[ 1.  5.  5. 11.  1.  7.  5.  7.  5.  3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [13]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [14]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)



64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [16]:
A = np.random.randint(0,10,(3,4,3,4))
print(A)
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[[[0 0 5 4]
   [7 3 7 3]
   [6 4 2 4]]

  [[4 5 0 8]
   [1 2 9 9]
   [3 2 5 3]]

  [[6 4 9 6]
   [0 7 9 0]
   [8 1 5 5]]

  [[3 2 8 6]
   [6 8 6 9]
   [7 1 1 4]]]


 [[[0 4 7 5]
   [6 1 8 7]
   [8 9 7 3]]

  [[3 1 3 8]
   [8 6 5 6]
   [3 4 5 0]]

  [[1 4 7 9]
   [1 7 6 7]
   [3 0 3 2]]

  [[3 2 1 3]
   [6 2 5 4]
   [7 3 0 0]]]


 [[[4 8 2 4]
   [5 1 0 0]
   [9 9 8 9]]

  [[9 2 4 8]
   [6 8 4 5]
   [9 5 5 2]]

  [[6 5 2 3]
   [6 4 1 1]
   [3 3 4 8]]

  [[5 7 4 0]
   [2 7 0 4]
   [3 9 3 1]]]]
[[45 51 60 61]
 [65 52 50 36]
 [59 67 46 45]]
[[45 51 60 61]
 [65 52 50 36]
 [59 67 46 45]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [17]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.57303139 0.53333827 0.46011663 0.57657429 0.55643554 0.64182141
 0.54387252 0.47821259 0.64559787 0.51537106]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [18]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([1.08260652, 1.27564496, 0.90150457, 1.4601835 , 2.18302012])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [19]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [20]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [ ]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [21]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 2, 72) ( 2, 81) ( 8, 58) ( 8, 72) (10, 66) (10, 80) (15, 42) (15, 43)
 (15, 86) (15, 99) (27, 69) (27, 75) (37, 87) (37, 95) (42, 99) (43, 86)
 (47, 89) (47, 90) (51, 85) (51, 92) (58, 72) (63, 82) (63, 88) (66, 80)
 (69, 75) (72, 81) (82, 88) (85, 92) (87, 95) (89, 90)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [22]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [23]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [24]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [25]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.83722664,  0.16018803, -0.1337759 , -0.1694134 ,  0.40240744,
        0.02232355,  0.04030517, -0.54962175, -0.3144197 ,  0.05353106,
        0.5139533 , -0.41535279,  0.55394289,  0.63248041, -0.17806686,
       -0.62936942,  0.17423656,  0.26771598, -0.82153181,  0.38533448,
        0.02623887, -0.86611646, -0.34003399,  0.42267911, -0.50593375,
        0.51601995, -0.21137433,  0.2235712 ,  0.03125638,  0.18431572,
       -0.54128412, -0.57599987, -0.17429665,  0.50531069,  0.16389955,
       -0.60475701, -0.20386453,  0.45701226,  0.95079058,  0.99727629,
        0.56446076,  0.64216955, -0.96036024, -0.56253413, -0.1910861 ,
       -0.27292385, -0.69182958,  0.26895329,  0.61872755,  0.35564746,
       -0.89016268, -0.33959929,  0.14151836,  0.59648665,  0.96038366,
        0.61659637, -0.13191366, -0.84021012, -0.82170357, -0.71145694,
        0.52639154,  0.23950549,  0.82608091,  0.30095671, -0.20344413,
        0.49123034,  0.76101446,  0.83691501,  0.52940092,  0.91

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [26]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[3.59636398 4.46741828 9.77395879 8.03099188 1.180437   0.60808313
 4.4336064  8.41008214 0.33476603 3.6179934 ]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [27]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 7.55209508  3.7269786   2.74538365  6.56607269  8.53991624  1.63953531
   1.90582461  0.1659059   4.96052545  5.16571395]
 [ 3.43380262 15.16660576 11.08440446  3.59596774  1.71455838 14.81360048
   1.90774446 11.74156407 16.56829736  8.1303355 ]
 [14.13234603  0.36746054  8.48785246  1.6900817  12.79234502  3.34363489
   8.5439523   4.04545113  8.81210023  3.84577685]
 [ 1.15938105 14.0259766   6.15776768  1.3469094   1.31249595 10.71391572
   4.28622276  6.94835006 11.78114985  4.19263411]
 [ 5.17441173  3.20867164  1.54340199 10.77937106  8.41203537  1.61815112
   0.55602447  3.83389974  0.96811642  8.26261423]
 [ 8.22686524  0.03299576  1.03081572 10.89961271 11.75350736  3.39489459
   2.46181244  4.5587895   0.22761816 10.1962103 ]
 [10.9792519   0.26811042  2.86656556  7.20416279 12.58066219  0.89749662
   5.28113456  1.18113307  3.59540579  7.87434326]
 [13.67427429  5.37127396  0.45496978 10.48188583 17.35335109  5.88422247
   7.86375982  5.18231491  0.42306311 12.97112531]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [28]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[0 4 4 4 8 7 8 1 7 3]
 [4 3 5 3 1 8 1 1 7 2]
 [1 6 4 2 3 0 8 3 1 9]
 [2 4 8 0 7 6 4 8 1 7]
 [6 0 3 0 6 7 1 0 8 1]
 [6 7 6 9 3 5 0 8 8 3]
 [4 4 4 2 4 3 4 1 2 3]
 [5 5 5 7 6 5 3 5 8 4]
 [3 0 8 0 3 4 0 5 0 3]
 [4 1 0 3 2 6 0 6 6 1]]
[[0 0 0 0 0]
 [0 0 4 4 4]
 [0 4 3 5 3]
 [0 1 6 4 2]
 [0 2 4 8 0]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [29]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [30]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [31]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

0


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [32]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[0 3 1]
   [0 3 3]
   [0 3 3]]

  [[3 1 4]
   [3 3 0]
   [3 3 2]]

  [[1 4 2]
   [3 0 0]
   [3 2 3]]

  [[4 2 3]
   [0 0 0]
   [2 3 1]]

  [[2 3 4]
   [0 0 2]
   [3 1 2]]

  [[3 4 2]
   [0 2 3]
   [1 2 0]]

  [[4 2 2]
   [2 3 0]
   [2 0 3]]

  [[2 2 1]
   [3 0 4]
   [0 3 0]]]


 [[[0 3 3]
   [0 3 3]
   [4 3 1]]

  [[3 3 0]
   [3 3 2]
   [3 1 4]]

  [[3 0 0]
   [3 2 3]
   [1 4 4]]

  [[0 0 0]
   [2 3 1]
   [4 4 3]]

  [[0 0 2]
   [3 1 2]
   [4 3 1]]

  [[0 2 3]
   [1 2 0]
   [3 1 2]]

  [[2 3 0]
   [2 0 3]
   [1 2 0]]

  [[3 0 4]
   [0 3 0]
   [2 0 3]]]


 [[[0 3 3]
   [4 3 1]
   [3 1 1]]

  [[3 3 2]
   [3 1 4]
   [1 1 0]]

  [[3 2 3]
   [1 4 4]
   [1 0 2]]

  [[2 3 1]
   [4 4 3]
   [0 2 0]]

  [[3 1 2]
   [4 3 1]
   [2 0 0]]

  [[1 2 0]
   [3 1 2]
   [0 0 1]]

  [[2 0 3]
   [1 2 0]
   [0 1 4]]

  [[0 3 0]
   [2 0 3]
   [1 4 1]]]


 [[[4 3 1]
   [3 1 1]
   [1 1 2]]

  [[3 1 4]
   [1 1 0]
   [1 2 0]]

  [[1 4 4]
   [1 0 2]
   [2 0 2]]

  [[4 4 3]
   [0 2 0]
   [0 2 4]]

  [[4 3 1]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [33]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 0  4  0  5 17]
 [ 4  5  6  8  6]
 [ 0  6  9 42  8]
 [ 5  8 42  3  4]
 [17  6  8  4  5]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [34]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)


[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [35]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [36]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [38]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9998 9997 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [37]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [39]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [40]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1 loop, best of 5: 3.72 s per loop
10 loops, best of 5: 143 ms per loop
10 loops, best of 5: 123 ms per loop


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [41]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 2 3 5 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [42]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[3 1 1]
 [3 4 3]
 [2 1 3]
 [4 4 2]
 [1 0 4]
 [2 3 4]
 [2 3 1]
 [3 4 2]
 [4 4 0]
 [0 2 1]]
[[3 1 1]
 [3 4 3]
 [2 1 3]
 [4 4 2]
 [1 0 4]
 [2 3 4]
 [2 3 1]
 [3 4 2]
 [4 4 0]
 [0 2 1]]
[[3 1 1]
 [3 4 3]
 [2 1 3]
 [4 4 2]
 [1 0 4]
 [2 3 4]
 [2 3 1]
 [3 4 2]
 [4 4 0]
 [0 2 1]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [44]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [43]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 1]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [45]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.2968761 , 0.31608021, 0.35744869, 0.21375795, 0.27912251,
        0.20671603, 0.22474178, 0.07483191, 0.19183554, 0.03824503],
       [0.20695101, 0.22033811, 0.24917589, 0.14900972, 0.19457506,
        0.14410082, 0.15666649, 0.05216499, 0.1337277 , 0.02666044],
       [0.39447832, 0.41999605, 0.47496501, 0.2840339 , 0.37088799,
        0.27467684, 0.29862881, 0.09943396, 0.25490418, 0.05081862],
       [0.78550858, 0.836321  , 0.94577843, 0.56558512, 0.73853412,
        0.54695279, 0.59464737, 0.19799878, 0.5075803 , 0.10119305],
       [0.68258947, 0.72674434, 0.82186041, 0.49148088, 0.64176971,
        0.4752898 , 0.51673533, 0.17205654, 0.44107598, 0.08793451],
       [0.28228454, 0.30054476, 0.33987997, 0.20325168, 0.26540355,
        0.19655586, 0.21369564, 0.0711539 , 0.18240675, 0.03636527],
       [0.27582267, 0.29366489, 0.33209966, 0.19859897, 0.25932811,
        0.19205644, 0.20880386, 0.06952509, 0.17823122, 0.03553282],
       [0.5845106 , 0.62232101, 0.7037701

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [47]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [46]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [48]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.22300065  0.20916695]
